pom.xml
https://issues.redhat.com/browse/DBZ-6304
=> DBZ-6304 Change MySQL Maven coordinates

src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java, src/main/java/io/debezium/connector/jdbc/dialect/DatabaseDialect.java, src/main/java/io/debezium/connector/jdbc/dialect/GeneralDatabaseDialect.java, src/main/java/io/debezium/connector/jdbc/dialect/db2/Db2DatabaseDialect.java, src/main/java/io/debezium/connector/jdbc/dialect/mysql/MySqlDatabaseDialect.java, src/main/java/io/debezium/connector/jdbc/dialect/oracle/OracleDatabaseDialect.java, src/main/java/io/debezium/connector/jdbc/dialect/postgres/PostgresDatabaseDialect.java, src/main/java/io/debezium/connector/jdbc/dialect/sqlserver/SqlServerDatabaseDialect.java, src/main/java/io/debezium/connector/jdbc/relational/TableId.java, src/test/java/io/debezium/connector/jdbc/TableNamingStrategyTest.java, src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkSchemaEvolutionTest.java, src/test/java/io/debezium/connector/jdbc/integration/oracle/JdbcSinkSchemaEvolutionIT.java, src/test/java/io/debezium/connector/jdbc/integration/postgres/JdbcSinkSchemaEvolutionIT.java, src/test/java/io/debezium/connector/jdbc/integration/sqlserver/JdbcSinkSchemaEvolutionIT.java
https://issues.redhat.com/browse/DBZ-6491
=> DBZ-6491 Parse schema/catalog values from `table.name.format`

pom.xml, src/main/java/io/debezium/connector/jdbc/JdbcSinkConnectorTask.java
https://issues.redhat.com/browse/DBZ-6463
=> DBZ-6463 Fix resolving TopicPartition during preCommit

src/main/java/io/debezium/connector/jdbc/JdbcSinkConnectorTask.java
closes: https://issues.redhat.com/browse/DBZ-6597
=> DBZ-6597 Reduce log verbosity

src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java, src/main/java/io/debezium/connector/jdbc/dialect/DatabaseDialect.java, src/main/java/io/debezium/connector/jdbc/dialect/GeneralDatabaseDialect.java, src/main/java/io/debezium/connector/jdbc/naming/DefaultTableNamingStrategy.java, src/main/java/io/debezium/connector/jdbc/naming/TableNamingStrategy.java, src/test/java/io/debezium/connector/jdbc/TableNamingStrategyTest.java, src/test/java/io/debezium/connector/jdbc/util/SinkRecordFactory.java
https://issues.redhat.com/browse/DBZ-6595
for example,
```
table.name.format: debezium_${source.table}
```
=> DBZ-6595 Use source field in table.name.format to resolve table name

src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java, src/main/java/io/debezium/connector/jdbc/JdbcSinkConnectorConfig.java, src/main/java/io/debezium/connector/jdbc/SinkRecordDescriptor.java, src/main/java/io/debezium/connector/jdbc/dialect/GeneralDatabaseDialect.java, src/main/java/io/debezium/connector/jdbc/naming/DefaultTableNamingStrategy.java, src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkPrimaryKeyModeTest.java
https://issues.redhat.com/browse/DBZ-6602
=> DBZ-6602: Support record header as primary_key

pom.xml
Related main PR https://github.com/debezium/debezium/pull/4671
=> DBZ-6659 properly declaring junit 5 dependency

src/main/java/io/debezium/connector/jdbc/JdbcSinkConnectorTask.java
closes: https://issues.redhat.com/browse/DBZ-6655
=> DBZ-6655 Log error and throw a DataException on a schema change record

src/main/java/io/debezium/connector/jdbc/dialect/mysql/MySqlDatabaseDialect.java
https://issues.redhat.com/browse/DBZ-6753
=> Update MySqlDatabaseDialect.java to fix misspell

src/main/java/io/debezium/connector/jdbc/SinkRecordDescriptor.java, src/main/java/io/debezium/connector/jdbc/type/AbstractType.java, src/main/java/io/debezium/connector/jdbc/util/SchemaUtils.java, src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkInsertModeTest.java
https://issues.redhat.com/browse/DBZ-6684
=> DBZ-6684 Rename back fields with avro_unicode

src/main/java/io/debezium/connector/jdbc/dialect/GeneralDatabaseDialect.java, src/test/java/io/debezium/connector/jdbc/integration/postgres/JdbcSinkInsertModeIT.java, src/test/java/io/debezium/connector/jdbc/util/SinkRecordFactory.java
closes: https://issues.redhat.com/browse/DBZ-6682
=> DBZ-6682 Correctly manage the 'quote.identifiers' property.

src/main/java/io/debezium/connector/jdbc/JdbcSinkConnectorTask.java, src/main/java/io/debezium/connector/jdbc/SinkRecordDescriptor.java, src/main/java/io/debezium/connector/jdbc/dialect/GeneralDatabaseDialect.java, src/main/java/io/debezium/connector/jdbc/dialect/postgres/PostgresDatabaseDialect.java, src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkDeleteEnabledTest.java, src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkInsertModeTest.java, src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkPrimaryKeyModeTest.java, src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkSchemaEvolutionTest.java, src/test/java/io/debezium/connector/jdbc/integration/postgres/JdbcSinkInsertModeIT.java, src/test/java/io/debezium/connector/jdbc/junit/TestHelper.java, src/test/java/io/debezium/connector/jdbc/util/SinkRecordFactory.java
https://issues.redhat.com/browse/DBZ-6831
=> DBZ-6831 Error with propagation source column name

src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java, src/main/java/io/debezium/connector/jdbc/JdbcSinkConnectorConfig.java, src/main/java/io/debezium/connector/jdbc/SinkRecordDescriptor.java, src/main/java/io/debezium/connector/jdbc/dialect/DatabaseDialect.java, src/main/java/io/debezium/connector/jdbc/dialect/GeneralDatabaseDialect.java, src/main/java/io/debezium/connector/jdbc/dialect/db2/Db2DatabaseDialect.java, src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkDeleteEnabledTest.java, src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkTest.java, src/test/java/io/debezium/connector/jdbc/integration/db2/JdbcSinkDeleteEnabledIT.java, src/test/java/io/debezium/connector/jdbc/util/SinkRecordBuilder.java, src/test/java/io/debezium/connector/jdbc/util/SinkRecordFactory.java
https://issues.redhat.com/browse/DBZ-6970
=> DBZ-6970 Debezium jdbc sink process truncate event failure

src/main/java/io/debezium/connector/jdbc/JdbcSinkConnectorTask.java
closes: https://issues.redhat.com/browse/DBZ-7069
=> DBZ-7069 Correctly manage errors to avoid potential connection leak

src/main/java/io/debezium/connector/jdbc/transforms/ConvertCloudEventToSaveableForm.java, src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkSaveConvertedCloudEventTest.java, src/test/java/io/debezium/connector/jdbc/transforms/ConvertCloudEventToSaveableFormTest.java, src/test/java/io/debezium/connector/jdbc/util/SinkRecordBuilder.java, src/test/java/io/debezium/connector/jdbc/util/SinkRecordFactory.java
https://issues.redhat.com/browse/DBZ-7130
=> DBZ-7130 `ConvertCloudEventToSaveableForm` can work with cloud events deserialized from JSON

src/main/java/io/debezium/connector/jdbc/RecordWriter.java, src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkInsertModeTest.java, src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkSchemaEvolutionTest.java
closes: https://issues.redhat.com/browse/DBZ-7191
=> DBZ-7191 Null value will be used instead of default for optional field

src/main/java/io/debezium/connector/jdbc/transforms/ConvertCloudEventToSaveableForm.java, src/test/java/io/debezium/connector/jdbc/transforms/ConvertCloudEventToSaveableFormTest.java
Please merge after https://github.com/debezium/debezium/pull/5034
=> DBZ-7159 Use CE validator

src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java, src/main/java/io/debezium/connector/jdbc/JdbcSinkConnectorTask.java, src/main/java/io/debezium/connector/jdbc/RecordWriter.java
closes: https://issues.redhat.com/browse/DBZ-7217
=> DBZ-7217 Add trace performance logs with execution times

src/main/java/io/debezium/connector/jdbc/JdbcSinkConnectorConfig.java, src/test/java/io/debezium/connector/jdbc/JdbcSinkConnectorConfigTest.java
https://issues.redhat.com/browse/DBZ-7431
=> DBZ-7431 Add `connection.provider` as configurable option

pom.xml
https://issues.redhat.com/browse/DBZ-7364
=> DBZ-7364 Include Oracle ojdbc8 in distribution

pom.xml
https://issues.redhat.com/browse/DBZ-7580
=> DBZ-7580 Correct Hibernate dependecies; remove unnecessary protobuf

src/main/java/io/debezium/connector/jdbc/transforms/ConvertCloudEventToSaveableForm.java
https://issues.redhat.com/browse/DBZ-7618
=> DBZ-7618 Implement Versioned interfaces in Transformation and Converter plugins

src/test/java/io/debezium/connector/jdbc/e2e/AbstractJdbcSinkPipelineIT.java, src/test/java/io/debezium/connector/jdbc/junit/jupiter/MySqlSinkDatabaseContextProvider.java, src/test/resources/logback-test.xml
https://issues.redhat.com/browse/DBZ-7651
=> DBZ-7651 Fix MySQL test failures

src/main/java/io/debezium/connector/jdbc/SinkRecordDescriptor.java, src/test/java/io/debezium/connector/jdbc/e2e/AbstractJdbcSinkPipelineIT.java, src/test/java/io/debezium/connector/jdbc/junit/jupiter/JdbcConnectionProvider.java, src/test/java/io/debezium/connector/jdbc/junit/jupiter/e2e/source/ValueBinder.java
https://issues.redhat.com/browse/DBZ-6900
=> DBZ-6900 Add test case for Oracle CLOB using UPSERT

pom.xml, src/main/java/io/debezium/connector/jdbc/dialect/mysql/MariaDbDatabaseDialect.java, src/main/java/io/debezium/connector/jdbc/dialect/mysql/MySqlDatabaseDialect.java, src/main/resources/META-INF/services/io.debezium.connector.jdbc.dialect.DatabaseDialectProvider
https://issues.redhat.com/browse/DBZ-7874
Supersedes #77
=> DBZ-7874 Separation of MariaDB dialect file

src/test/java/io/debezium/connector/jdbc/e2e/AbstractJdbcSinkPipelineIT.java, src/test/java/io/debezium/connector/jdbc/e2e/JdbcSinkPipelineToOracleIT.java
https://issues.redhat.com/browse/DBZ-7949
=> DBZ-7949 Fix JDBC test failures with TIME changes

src/main/java/io/debezium/connector/jdbc/SinkRecordDescriptor.java, src/test/java/io/debezium/connector/jdbc/integration/AbstractJdbcSinkPrimaryKeyModeTest.java
closes: https://issues.redhat.com/browse/DBZ-8018
A doc PR will follow to add a note about possible failures due to certain data types are not permissible across various database vendors to be used in Primary Key configurations.
=> DBZ-8018 Use all record fields as primary key columns when no primary key fields are specified
